"""add tactics and club management

Revision ID: 002_add_tactics_and_club_management
Revises: add_personalized_development
Create Date: 2024-02-12

"""
from alembic import op
import sqlalchemy as sa
from datetime import date


# revision identifiers
revision = '002_add_tactics_and_club_management'
down_revision = 'add_personalized_development'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create facilities table
    op.create_table(
        'facilities',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('club_id', sa.Integer(), sa.ForeignKey('clubs.id'), nullable=False, index=True),
        sa.Column('facility_type', sa.Enum(
            'YOUTH_ACADEMY', 'TRAINING_GROUND', 'DATA_ANALYTICS', 
            'MEDICAL_CENTER', 'SCOUTING_NETWORK', 'STADIUM',
            name='facilitytype'
        ), nullable=False),
        sa.Column('level', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('upgrade_cost', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('weekly_maintenance', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_upgraded', sa.Date(), nullable=True),
    )
    
    # Create index on facility_type for faster queries
    op.create_index('ix_facilities_facility_type', 'facilities', ['facility_type'])
    
    # 2. Create staff table
    op.create_table(
        'staff',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('club_id', sa.Integer(), sa.ForeignKey('clubs.id'), nullable=True, index=True),
        sa.Column('first_name', sa.String(100), nullable=False),
        sa.Column('last_name', sa.String(100), nullable=False),
        sa.Column('nationality', sa.String(100), server_default='Unknown'),
        sa.Column('birth_date', sa.Date(), nullable=True),
        sa.Column('role', sa.Enum(
            'HEAD_COACH', 'ASSISTANT_MANAGER', 'GOALKEEPER_COACH',
            'FITNESS_COACH', 'CHIEF_SCOUT', 'HEAD_PHYSIO',
            name='staffrole'
        ), nullable=False),
        sa.Column('ability', sa.Integer(), server_default='50', nullable=False),
        sa.Column('coaching_ability', sa.Integer(), server_default='50', nullable=False),
        sa.Column('scouting_ability', sa.Integer(), server_default='50', nullable=False),
        sa.Column('medical_ability', sa.Integer(), server_default='50', nullable=False),
        sa.Column('salary', sa.Integer(), server_default='1000', nullable=False),  # Weekly wage
        sa.Column('contract_until', sa.Date(), nullable=True),
        sa.Column('reputation', sa.Integer(), server_default='1000', nullable=False),
        sa.Column('has_release_clause', sa.Boolean(), server_default='0'),
        sa.Column('release_clause_amount', sa.Integer(), nullable=True),
        sa.Column('is_hired', sa.Boolean(), server_default='0'),
    )
    
    # Create indexes on staff
    op.create_index('ix_staff_role', 'staff', ['role'])
    op.create_index('ix_staff_club_hired', 'staff', ['club_id', 'is_hired'])
    
    # 3. Create sponsors table
    op.create_table(
        'sponsors',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('club_id', sa.Integer(), sa.ForeignKey('clubs.id'), nullable=True, index=True),
        sa.Column('name', sa.String(100), nullable=False, unique=True),
        sa.Column('industry', sa.String(100), nullable=False),
        sa.Column('country', sa.String(100), server_default=''),
        sa.Column('level', sa.Enum(
            'GLOBAL', 'PREMIUM', 'MAJOR', 'REGIONAL', 'LOCAL',
            name='sponsorlevel'
        ), server_default='LOCAL'),
        sa.Column('sponsor_type', sa.Enum(
            'MAIN_SPONSOR', 'KIT_SPONSOR', 'STADIUM_NAMING',
            'SLEEVE_SPONSOR', 'TRAINING_KIT', 'OFFICIAL_PARTNER',
            name='sponsortype'
        ), server_default='OFFICIAL_PARTNER'),
        sa.Column('base_annual_payment', sa.Integer(), server_default='0', nullable=False),
        sa.Column('performance_bonus_rate', sa.Float(), server_default='0.0', nullable=False),
        sa.Column('max_annual_bonus', sa.Integer(), server_default='0', nullable=False),
        sa.Column('contract_start', sa.Date(), nullable=True),
        sa.Column('contract_end', sa.Date(), nullable=True),
        sa.Column('status', sa.Enum(
            'ACTIVE', 'EXPIRED', 'NEGOTIATING', 'TERMINATED', 'PENDING',
            name='contractstatus'
        ), server_default='PENDING'),
        sa.Column('reputation', sa.Integer(), server_default='50', nullable=False),
        sa.Column('min_club_reputation', sa.Integer(), server_default='1000', nullable=False),
        sa.Column('preferred_leagues', sa.Text(), server_default=''),
        sa.Column('negotiation_count', sa.Integer(), server_default='0', nullable=False),
        sa.Column('last_negotiation_date', sa.Date(), nullable=True),
        sa.Column('matches_sponsored', sa.Integer(), server_default='0', nullable=False),
        sa.Column('goals_scored_in_sponsored_matches', sa.Integer(), server_default='0', nullable=False),
        sa.Column('wins_in_sponsored_matches', sa.Integer(), server_default='0', nullable=False),
        sa.Column('auto_renewal', sa.Boolean(), server_default='0'),
    )
    
    # Create indexes on sponsors
    op.create_index('ix_sponsors_level', 'sponsors', ['level'])
    op.create_index('ix_sponsors_status', 'sponsors', ['status'])
    op.create_index('ix_sponsors_club_status', 'sponsors', ['club_id', 'status'])
    
    # 4. Add new columns to clubs table
    op.add_column('clubs', sa.Column(
        'facility_maintenance',
        sa.Integer(),
        server_default='0',
        nullable=False
    ))
    
    op.add_column('clubs', sa.Column(
        'staff_wages',
        sa.Integer(),
        server_default='0',
        nullable=False
    ))
    
    op.add_column('clubs', sa.Column(
        'sponsor_income',
        sa.Integer(),
        server_default='0',
        nullable=False
    ))
    
    # ### end Alembic commands ###
    
    # Initialize default data for existing clubs
    _initialize_default_data()


def _initialize_default_data():
    """Initialize default data for existing clubs."""
    connection = op.get_bind()
    
    # Get all existing clubs
    result = connection.execute(sa.text("SELECT id FROM clubs"))
    clubs = result.fetchall()
    
    if not clubs:
        return
    
    # Insert default facilities for each club
    facility_types = [
        ('TRAINING_GROUND', 5),  # 默认训练设施等级5
        ('YOUTH_ACADEMY', 3),    # 默认青训设施等级3
    ]
    
    for club in clubs:
        club_id = club[0]
        
        # Create default facilities
        for facility_type, level in facility_types:
            # Calculate upgrade and maintenance costs based on level
            upgrade_cost = _calculate_upgrade_cost(facility_type, level)
            maintenance_cost = _calculate_maintenance_cost(facility_type, level)
            
            connection.execute(
                sa.text("""
                    INSERT INTO facilities (club_id, facility_type, level, upgrade_cost, weekly_maintenance, last_upgraded)
                    VALUES (:club_id, :facility_type, :level, :upgrade_cost, :maintenance_cost, :last_upgraded)
                """),
                {
                    'club_id': club_id,
                    'facility_type': facility_type,
                    'level': level,
                    'upgrade_cost': upgrade_cost,
                    'maintenance_cost': maintenance_cost,
                    'last_upgraded': date.today()
                }
            )
        
        # Create default head coach for each club
        connection.execute(
            sa.text("""
                INSERT INTO staff (club_id, first_name, last_name, nationality, role, ability, 
                                 coaching_ability, salary, contract_until, reputation, is_hired)
                VALUES (:club_id, :first_name, :last_name, :nationality, :role, :ability,
                        :coaching_ability, :salary, :contract_until, :reputation, :is_hired)
            """),
            {
                'club_id': club_id,
                'first_name': 'Default',
                'last_name': 'Coach',
                'nationality': 'Unknown',
                'role': 'HEAD_COACH',
                'ability': 60,
                'coaching_ability': 60,
                'salary': 5000,
                'contract_until': date(date.today().year + 2, 6, 30),
                'reputation': 1500,
                'is_hired': True
            }
        )
    
    # Update club totals
    connection.execute(
        sa.text("""
            UPDATE clubs 
            SET facility_maintenance = (
                SELECT COALESCE(SUM(weekly_maintenance), 0) 
                FROM facilities 
                WHERE facilities.club_id = clubs.id
            )
        """)
    )
    
    connection.execute(
        sa.text("""
            UPDATE clubs 
            SET staff_wages = (
                SELECT COALESCE(SUM(salary), 0) 
                FROM staff 
                WHERE staff.club_id = clubs.id AND staff.is_hired = 1
            )
        """)
    )


def _calculate_upgrade_cost(facility_type: str, level: int) -> int:
    """Calculate upgrade cost for a facility level."""
    base_costs = {
        'YOUTH_ACADEMY': 1_000_000,
        'TRAINING_GROUND': 800_000,
        'DATA_ANALYTICS': 600_000,
        'MEDICAL_CENTER': 700_000,
        'SCOUTING_NETWORK': 500_000,
        'STADIUM': 5_000_000,
    }
    import math
    base_cost = base_costs.get(facility_type, 500_000)
    return int(base_cost * math.pow(1.5, level))


def _calculate_maintenance_cost(facility_type: str, level: int) -> int:
    """Calculate weekly maintenance cost for a facility level."""
    base_maintenance = {
        'YOUTH_ACADEMY': 50_000,
        'TRAINING_GROUND': 40_000,
        'DATA_ANALYTICS': 30_000,
        'MEDICAL_CENTER': 35_000,
        'SCOUTING_NETWORK': 25_000,
        'STADIUM': 200_000,
    }
    base = base_maintenance.get(facility_type, 25_000)
    multiplier = 1.0 + ((level - 1) / 19) * 1.5
    return int(base * multiplier)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop new columns from clubs table
    op.drop_column('clubs', 'sponsor_income')
    op.drop_column('clubs', 'staff_wages')
    op.drop_column('clubs', 'facility_maintenance')
    
    # Drop sponsors table
    op.drop_index('ix_sponsors_club_status', table_name='sponsors')
    op.drop_index('ix_sponsors_status', table_name='sponsors')
    op.drop_index('ix_sponsors_level', table_name='sponsors')
    op.drop_table('sponsors')
    
    # Drop staff table
    op.drop_index('ix_staff_club_hired', table_name='staff')
    op.drop_index('ix_staff_role', table_name='staff')
    op.drop_table('staff')
    
    # Drop facilities table
    op.drop_index('ix_facilities_facility_type', table_name='facilities')
    op.drop_table('facilities')
    
    # Drop enum types (PostgreSQL specific - SQLite will ignore)
    # These are automatically cleaned up when tables are dropped in most databases
    
    # ### end Alembic commands ###
