#!/usr/bin/env python3
"""
Import the compact generated dataset into the database.

This script imports the ~2500 player dataset generated by compact_fifa_dataset.py,
providing a good balance between data quality and quantity for testing/development.

Usage:
    python scripts/import_compact_data.py
"""

import asyncio
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from sqlalchemy import select

from fm_manager.core import init_db, close_db, get_session_maker
from fm_manager.core.models import League, Club, Player, Position, Foot
from fm_manager.data.fifa_importer import FIFAImporter
from fm_manager.data.importer import DataImporter


# League configurations
LEAGUE_CONFIGS = {
    "Premier League": {
        "country": "England",
        "tier": 1,
        "teams_count": 20,
        "champions_league_spots": 4,
    },
    "La Liga": {
        "country": "Spain",
        "tier": 1,
        "teams_count": 20,
        "champions_league_spots": 4,
    },
    "Bundesliga": {
        "country": "Germany",
        "tier": 1,
        "teams_count": 18,
        "champions_league_spots": 4,
    },
    "Serie A": {
        "country": "Italy",
        "tier": 1,
        "teams_count": 20,
        "champions_league_spots": 4,
    },
    "Ligue 1": {
        "country": "France",
        "tier": 1,
        "teams_count": 18,
        "champions_league_spots": 3,
    },
}


async def import_compact_dataset():
    """Import the compact dataset into the database."""
    csv_file = project_root / "fm_manager" / "data" / "seeds" / "compact_players.csv"
    
    if not csv_file.exists():
        print(f"❌ Dataset not found: {csv_file}")
        print("   Run: python fm_manager/data/compact_fifa_dataset.py")
        return False
    
    print("🚀 Initializing database...")
    await init_db()
    
    session_maker = get_session_maker()
    
    async with session_maker() as session:
        importer = DataImporter(session)
        
        # Parse FIFA data
        print("📊 Parsing compact dataset...")
        fifa_importer = FIFAImporter(csv_file)
        fifa_players = fifa_importer.parse_csv()
        print(f"   Found {len(fifa_players)} players")
        
        # Create leagues
        print("\n🌍 Creating leagues...")
        leagues = {}
        for league_name, config in LEAGUE_CONFIGS.items():
            # Check if exists
            result = await session.execute(
                select(League).where(League.name == league_name)
            )
            existing = result.scalar_one_or_none()
            
            if existing:
                leagues[league_name] = existing.id
                print(f"   {league_name} (exists)")
            else:
                league_data = {
                    "name": league_name,
                    "short_name": league_name[:3].upper(),
                    "country": config["country"],
                    "tier": config["tier"],
                    "teams_count": config["teams_count"],
                    "champions_league_spots": config["champions_league_spots"],
                }
                result = await importer.import_leagues([league_data])
                leagues[league_name] = result[0].id
                print(f"   {league_name} (created)")
        
        # Get unique clubs with their leagues
        clubs_data = {}
        for player in fifa_players:
            if player.club not in clubs_data:
                clubs_data[player.club] = {
                    "league": player.league,
                    "reputation": _estimate_reputation(player.club),
                }
        
        print(f"\n🏟️ Creating {len(clubs_data)} clubs...")
        clubs = {}
        for i, (club_name, data) in enumerate(clubs_data.items()):
            # Check if exists
            result = await session.execute(
                select(Club).where(Club.name == club_name)
            )
            existing = result.scalar_one_or_none()
            
            if existing:
                clubs[club_name] = existing.id
            else:
                reputation = data["reputation"]
                league_id = leagues.get(data["league"])
                
                club_data = {
                    "name": club_name,
                    "short_name": club_name[:3].upper() if len(club_name) > 3 else club_name.upper(),
                    "reputation": reputation,
                    "balance": reputation * 100000,
                    "transfer_budget": reputation * 50000,
                    "wage_budget": reputation * 5000,
                    "league_id": league_id,
                }
                result = await importer.import_clubs([club_data])
                clubs[club_name] = result[0].id
            
            if (i + 1) % 20 == 0:
                print(f"   {i + 1}/{len(clubs_data)} clubs...")
        
        await session.commit()
        
        # Create players
        print(f"\n👤 Creating {len(fifa_players)} players...")
        
        batch_size = 100
        for i in range(0, len(fifa_players), batch_size):
            batch = fifa_players[i:i+batch_size]
            
            for fifa_player in batch:
                club_id = clubs.get(fifa_player.club)
                db_player = fifa_importer.to_db_player(fifa_player, club_id)
                session.add(db_player)
            
            await session.commit()
            print(f"   {min(i + batch_size, len(fifa_players))}/{len(fifa_players)} players...")
        
        # Print summary
        print("\n" + "="*50)
        print("📈 IMPORT SUMMARY")
        print("="*50)
        
        result = await session.execute(select(League))
        league_count = len(result.scalars().all())
        
        result = await session.execute(select(Club))
        club_count = len(result.scalars().all())
        
        result = await session.execute(select(Player))
        player_count = len(result.scalars().all())
        
        print(f"   Leagues: {league_count}")
        print(f"   Clubs:   {club_count}")
        print(f"   Players: {player_count}")
        
        # Show top clubs by total squad value
        print("\n🏆 Top 10 Clubs by Total Squad Value:")
        from sqlalchemy import func
        result = await session.execute(
            select(
                Club.name,
                func.count(Player.id).label("squad_size"),
                func.sum(Player.market_value).label("total_value"),
                func.avg(Player.current_ability).label("avg_rating"),
            )
            .join(Player, Club.id == Player.club_id)
            .group_by(Club.id)
            .order_by(func.sum(Player.market_value).desc())
            .limit(10)
        )
        
        for row in result:
            print(f"   {row.name:25} | {row.squad_size:2} players | "
                  f"€{row.total_value/1_000_000:6.1f}M | Avg: {row.avg_rating:.1f}")
    
    await close_db()
    print("\n✅ Import complete!")
    return True


def _estimate_reputation(club_name: str) -> int:
    """Estimate club reputation based on name (simplified)."""
    top_clubs = [
        "Manchester City", "Real Madrid", "Bayern Munich", "Barcelona",
        "Liverpool", "Paris Saint-Germain", "Manchester United",
        "Arsenal", "Chelsea", "Inter Milan", "AC Milan", "Juventus",
        "Atletico Madrid", "Borussia Dortmund", "RB Leipzig",
    ]
    
    if club_name in top_clubs[:6]:
        return 9500
    elif club_name in top_clubs:
        return 8800
    else:
        return 7500


if __name__ == "__main__":
    asyncio.run(import_compact_dataset())
